title: La carriera di Programmatore è una frode
description: Quello che dovreste sapere prima di intraprendere una delle peggiori carriere sul mercato delle professioni specializzate

url: http://arashleto.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: arashleto
   twitter: arashleto
   facebook: arashleto
   email: arashleto@gmail.com

google_analytics: ""
